//array contains all the movie trailer youtube link use in the website

const gametrailer = [
    {name:"Valheim", url:'IAMPr9kytfk'},
    {name:"Resident Evil: Village", url:'RdzkmBBnHbo'},
    {name:"Outriders",url:'S8TaAcA0_Ug'},
    {name:"It Takes Two",url:'yZ2VB6nbsUI'},
    {name:"The Medium",url:'f5NSArpKhTo'},
    {name:"Mass Effect: Legendary Edition",url:'-B6byqlt6U8'},
    {name:"Fall Guys: Ultimate Knockout",url:'FcITAzKW3fY'},
    {name:"The Last of Us Part II",url:'btmN-bWwv0A'},
    {name:"DOOM Eternal",url:'6eMhs6VFG0o'},
    {name:"Hades",url:'ClZe5x8Tfiw'},
    {name:"Ori and the Will of the Wisps",url:'fXUrR6EiEcY'},
    {name:"METAL SLUG 3",url:'y_D831mBAYg'},
    {name:"METAL SLUG",url:'hWe0Wg4dyIk'},
    {name:"THE KING OF FIGHTERS 2002",url:'iFnRvk-GG34'},
    {name:"METAL SLUG 2",url:'69xfXl3rBoM'},
    {name:"Pac-man",url:'dScq4P5gn4A'},
    {name:"Double Dragon",url:'rTy6NS7Bciw'},
    {name:"Garou: Mark of the Wolves",url:'EvnjoAjYBb4'},
    {name:"Life is Strange",url:'K8JPS7xDGFU'},
    {name:"Stardew Valley",url:'y9Z0q4HsbW0'},
    {name:"Mortal Kombat X",url:'6W94EWRHy2k'},
    {name:"Layers of Fear",url:'3BARFQyWq_s'},
    {name:"INSIDE",url:'vPcolQbesz4'},
    {name:"Grim Fandango Remastered",url:'QYQEf0uaWww'},
    {name:"The Witness",url:'Mj3nCfB64AI'},
    {name:"Disco Elysium: Final Cut",url:'gRTe4yXooGQ'},
    {name:"Steven Universe: Unleash the Light",url:'GxWqPMI1gZk'},
    {name:"MIR4",url:'jXax51AiSPA'},
    {name:"Card Hog",url:'uRaZdRvVKpE'},
    {name:"Overboard! (2021)",url:'sP8P6RtMVOk'},
    {name:"Pokémon Unite",url:'fX2UlkPAtv8'},
    {name:"SaGa Frontier Remastered",url:'_AJvOPRa-rM'},
    {name:"Cyberpunk 2077",url:'I_aMjOBhThs'},
]; 

export default gametrailer;